[project]
name = "perika-game"
version = "0.1.0"
description = "Simple console game, for training rapid typing in you favorite shell."
authors = [
    { name = "Arsen Gumin", email = "gumin@live.ru" }
]

dependencies = [
    "typer>=0.12.3",
    "requests>=2.32.3",
    "rich>=13.7.1",
]
readme = "README.md"
requires-python = ">= 3.9"
license = 'MIT'

[project.scripts]
perika = "perika.ui.cli.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "mypy>=1.11.1",
    "gitlint>=0.19.1",
    "git-cliff>=2.4.0",
    "types-requests>=2.32.0.20240712",
    "ruff>=0.6.2",
    "pyright>=1.1.377",
    "bandit>=1.7.9",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["perika"]
